crfcut and tests
PyThaiNLP/pythainlp pull request #337
Opened 2019-12-17 07:51 UTC by cstorm125

CRFCut -- Thai sentence segmentation with conditional random field, default trained on TED dataset
ORCHID - space-correct accuracy 87% vs 95% state-of-the-art (Zhou et al, 2016; https://www.aclweb.org/anthology/C16-1031.pdf)
TED dataset - space-correct accuracy 82%
See development notebooks at https://github.com/vistec-AI/ted_crawler;
POS features are not used due to unreliable POS tagging available

2019-12-17 07:52 UTC, pep8speaks commented
Hello @cstorm125! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





* In the file [`pythainlp/tokenize/__init__.py`](https://github.com/PyThaiNLP/pythainlp/blob/5d7a807511490e6a79d5d65bc44db13ae09e0c61/pythainlp/tokenize/__init__.py):

> [Line 187:80](https://github.com/PyThaiNLP/pythainlp/blob/5d7a807511490e6a79d5d65bc44db13ae09e0c61/pythainlp/tokenize/__init__.py#L187): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 228:80](https://github.com/PyThaiNLP/pythainlp/blob/5d7a807511490e6a79d5d65bc44db13ae09e0c61/pythainlp/tokenize/__init__.py#L228): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (100 > 79 characters)
> [Line 234:80](https://github.com/PyThaiNLP/pythainlp/blob/5d7a807511490e6a79d5d65bc44db13ae09e0c61/pythainlp/tokenize/__init__.py#L234): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (103 > 79 characters)

* In the file [`pythainlp/tokenize/crfcut.py`](https://github.com/PyThaiNLP/pythainlp/blob/5d7a807511490e6a79d5d65bc44db13ae09e0c61/pythainlp/tokenize/crfcut.py):

> [Line 3:80](https://github.com/PyThaiNLP/pythainlp/blob/5d7a807511490e6a79d5d65bc44db13ae09e0c61/pythainlp/tokenize/crfcut.py#L3): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (98 > 79 characters)
> [Line 4:80](https://github.com/PyThaiNLP/pythainlp/blob/5d7a807511490e6a79d5d65bc44db13ae09e0c61/pythainlp/tokenize/crfcut.py#L4): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (125 > 79 characters)
> [Line 24:80](https://github.com/PyThaiNLP/pythainlp/blob/5d7a807511490e6a79d5d65bc44db13ae09e0c61/pythainlp/tokenize/crfcut.py#L24): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 79 characters)
> [Line 26:80](https://github.com/PyThaiNLP/pythainlp/blob/5d7a807511490e6a79d5d65bc44db13ae09e0c61/pythainlp/tokenize/crfcut.py#L26): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> [Line 27:80](https://github.com/PyThaiNLP/pythainlp/blob/5d7a807511490e6a79d5d65bc44db13ae09e0c61/pythainlp/tokenize/crfcut.py#L27): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 32:80](https://github.com/PyThaiNLP/pythainlp/blob/5d7a807511490e6a79d5d65bc44db13ae09e0c61/pythainlp/tokenize/crfcut.py#L32): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 48:80](https://github.com/PyThaiNLP/pythainlp/blob/5d7a807511490e6a79d5d65bc44db13ae09e0c61/pythainlp/tokenize/crfcut.py#L48): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (102 > 79 characters)
> [Line 52:80](https://github.com/PyThaiNLP/pythainlp/blob/5d7a807511490e6a79d5d65bc44db13ae09e0c61/pythainlp/tokenize/crfcut.py#L52): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (94 > 79 characters)

* In the file [`tests/test_tokenize.py`](https://github.com/PyThaiNLP/pythainlp/blob/5d7a807511490e6a79d5d65bc44db13ae09e0c61/tests/test_tokenize.py):

> [Line 237:80](https://github.com/PyThaiNLP/pythainlp/blob/5d7a807511490e6a79d5d65bc44db13ae09e0c61/tests/test_tokenize.py#L237): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (96 > 79 characters)
> [Line 240:80](https://github.com/PyThaiNLP/pythainlp/blob/5d7a807511490e6a79d5d65bc44db13ae09e0c61/tests/test_tokenize.py#L240): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (108 > 79 characters)
> [Line 243:80](https://github.com/PyThaiNLP/pythainlp/blob/5d7a807511490e6a79d5d65bc44db13ae09e0c61/tests/test_tokenize.py#L243): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (107 > 79 characters)
> [Line 243:90](https://github.com/PyThaiNLP/pythainlp/blob/5d7a807511490e6a79d5d65bc44db13ae09e0c61/tests/test_tokenize.py#L243): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 246:80](https://github.com/PyThaiNLP/pythainlp/blob/5d7a807511490e6a79d5d65bc44db13ae09e0c61/tests/test_tokenize.py#L246): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (91 > 79 characters)
> [Line 249:73](https://github.com/PyThaiNLP/pythainlp/blob/5d7a807511490e6a79d5d65bc44db13ae09e0c61/tests/test_tokenize.py#L249): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 249:80](https://github.com/PyThaiNLP/pythainlp/blob/5d7a807511490e6a79d5d65bc44db13ae09e0c61/tests/test_tokenize.py#L249): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (90 > 79 characters)

2019-12-19 01:30 UTC, bact commented
How big is the model? If it's not that big I would suggest to include it in the module, so we will less dependent on the network during runtime.

2019-12-19 05:04 UTC, cstorm125 commented
@bact The model is 5MB so I agree we can include it as battery. Is everyone okay with having some model files in the library? @artificiala @wannaphongcom

2019-12-19 11:21 UTC, bact commented
For reference on model size https://github.com/PyThaiNLP/pythainlp/issues/298

2019-12-19 12:04 UTC, wannaphongcom commented on pythainlp/tokenize/__init__.py
> +        * *crfcut* - split by CRF trained on TED dataset
`* *crfcut* - split by CRF trained on TED dataset` -> `* *crfcut* (default) - split by CRF trained on TED dataset`

2019-12-19 12:04 UTC, wannaphongcom commented on pythainlp/tokenize/__init__.py
>          * *whitespace+newline* (default) - split by whitespace token \
`* *whitespace+newline* (default) - split by whitespace token` -> `* *whitespace+newline* - split by whitespace token`

2019-12-20 10:56 UTC, bact requested changes
I have add few words to STARTERS and ENDERS. May require retrain and reupload of the model.
Apart of that, I think we're good to go.

Please also kindly update the table here: https://github.com/PyThaiNLP/pythainlp/issues/298 thx

Great work! Another step towards full pipeline.

2019-12-20 17:35 UTC, merged

2019-12-20 17:45 UTC, wannaphongcom commented
:100:

2019-12-20 18:05 UTC, bact commented
Next step is to convert https://github.com/vistec-AI/ted_crawler/blob/master/sentenceseg_ted.ipynb to a commandline script and maybe put it in `bin/` directory. So people can train their own model.