Delete deprecated code
PyThaiNLP/pythainlp pull request #376
Opened 2020-04-09 09:50 UTC by wannaphong

- delete thaicheck
- delete deletetone
- delete dict_word_tokenize

2020-04-10 19:21 UTC, bact commented on tests/test_tokenize.py
>          # https://bugs.python.org/issue29620
Should delete comments in line 103-105 as well.

2020-04-10 19:22 UTC, bact commented on tests/test_util.py
>          # https://bugs.python.org/issue29620
Should delete comments in line 252-254 as well.

2020-04-10 19:22 UTC, bact commented on tests/test_util.py
>          # https://bugs.python.org/issue29620
Should delete comments in line 326-328 as well.

2020-04-10 19:23 UTC, bact requested changes
Great.
Just remove the comments that related to the functions to be removed as well.

2020-04-11 05:35 UTC, pep8speaks commented
Hello @wannaphong! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:









* In the file [`tests/test_tokenize.py`](https://github.com/PyThaiNLP/pythainlp/blob/96744d32c823dd13e47be020d5065d04426b305c/tests/test_tokenize.py):

> [Line 101:1](https://github.com/PyThaiNLP/pythainlp/blob/96744d32c823dd13e47be020d5065d04426b305c/tests/test_tokenize.py#L101): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2020-04-11 05:37 UTC, wannaphong commented
> 
> 
> Great.
> Just remove the comments that related to the functions to be removed as well.

Done 🌷

2020-04-14 21:57 UTC, bact approved these changes
Nice

2020-04-15 06:03 UTC, merged