Add clause tokenize model
PyThaiNLP/pythainlp pull request #479
Opened 2020-09-16 20:46 UTC by wannaphong

Clause tokenize model trained from LST20 Corpus with CRF model.
LST20 Corpus from National Electronics and Computer Technology Center, Thailand. It can download dataset from [https://aiforthai.in.th/corpus.php](https://aiforthai.in.th/corpus.php).

Model train by Mr.Wannaphong Phatthiyaphaibun

Model License : CC-0

**Code**

- Model File : https://github.com/PyThaiNLP/pythainlp-corpus/releases/tag/lst20-cls-v0.1
- Train script : https://github.com/PyThaiNLP/pythainlp_notebook/blob/master/cls/lst20.ipynb
- Google Colab : [https://colab.research.google.com/drive/13sKMQN6FbI9YhyN3rVW9Ydg9bUjKk0JP?usp=sharing](https://colab.research.google.com/drive/13sKMQN6FbI9YhyN3rVW9Ydg9bUjKk0JP?usp=sharing)

**TODO**

- [] document
- [] test

2020-09-16 20:46 UTC, pep8speaks commented
Hello @wannaphong! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pythainlp/tokenize/lst20.py`](https://github.com/PyThaiNLP/pythainlp/blob/63b4452864e75411b5467f339f637b01df94da41/pythainlp/tokenize/lst20.py):

> [Line 7:1](https://github.com/PyThaiNLP/pythainlp/blob/63b4452864e75411b5467f339f637b01df94da41/pythainlp/tokenize/lst20.py#L7): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 11:13](https://github.com/PyThaiNLP/pythainlp/blob/63b4452864e75411b5467f339f637b01df94da41/pythainlp/tokenize/lst20.py#L11): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 13:23](https://github.com/PyThaiNLP/pythainlp/blob/63b4452864e75411b5467f339f637b01df94da41/pythainlp/tokenize/lst20.py#L13): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 14:17](https://github.com/PyThaiNLP/pythainlp/blob/63b4452864e75411b5467f339f637b01df94da41/pythainlp/tokenize/lst20.py#L14): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 21:37](https://github.com/PyThaiNLP/pythainlp/blob/63b4452864e75411b5467f339f637b01df94da41/pythainlp/tokenize/lst20.py#L21): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 25:31](https://github.com/PyThaiNLP/pythainlp/blob/63b4452864e75411b5467f339f637b01df94da41/pythainlp/tokenize/lst20.py#L25): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 31:37](https://github.com/PyThaiNLP/pythainlp/blob/63b4452864e75411b5467f339f637b01df94da41/pythainlp/tokenize/lst20.py#L31): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 35:31](https://github.com/PyThaiNLP/pythainlp/blob/63b4452864e75411b5467f339f637b01df94da41/pythainlp/tokenize/lst20.py#L35): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 38:1](https://github.com/PyThaiNLP/pythainlp/blob/63b4452864e75411b5467f339f637b01df94da41/pythainlp/tokenize/lst20.py#L38): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 41:1](https://github.com/PyThaiNLP/pythainlp/blob/63b4452864e75411b5467f339f637b01df94da41/pythainlp/tokenize/lst20.py#L41): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 42:27](https://github.com/PyThaiNLP/pythainlp/blob/63b4452864e75411b5467f339f637b01df94da41/pythainlp/tokenize/lst20.py#L42): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 42:34](https://github.com/PyThaiNLP/pythainlp/blob/63b4452864e75411b5467f339f637b01df94da41/pythainlp/tokenize/lst20.py#L42): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 44:1](https://github.com/PyThaiNLP/pythainlp/blob/63b4452864e75411b5467f339f637b01df94da41/pythainlp/tokenize/lst20.py#L44): [E305](https://duckduckgo.com/?q=pep8%20E305) expected 2 blank lines after class or function definition, found 1
> [Line 48:1](https://github.com/PyThaiNLP/pythainlp/blob/63b4452864e75411b5467f339f637b01df94da41/pythainlp/tokenize/lst20.py#L48): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 55:10](https://github.com/PyThaiNLP/pythainlp/blob/63b4452864e75411b5467f339f637b01df94da41/pythainlp/tokenize/lst20.py#L55): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 56:10](https://github.com/PyThaiNLP/pythainlp/blob/63b4452864e75411b5467f339f637b01df94da41/pythainlp/tokenize/lst20.py#L56): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 63:21](https://github.com/PyThaiNLP/pythainlp/blob/63b4452864e75411b5467f339f637b01df94da41/pythainlp/tokenize/lst20.py#L63): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2020-09-16 20:55 UTC, wannaphong commented
# Model Card - LST20 CLS

**Model Details**
- Developed by Mr.Wannaphong Phatthiyaphaibun
- CRF Model
**Intended Use**
...
**Factors**
...
**Metrics**
...
**Evaluation Data**
...
**Training Data**
...
**Quantitative Analyses**
...
**Ethical Considerations**
...
**Caveats and Recommendations**
...

2020-10-03 02:59 UTC, bact requested changes
trying to make the feature names more consistent.

2020-10-03 02:59 UTC, bact commented on pythainlp/tokenize/crfcls.py
> +        "word.isdigit()": curr_word.isdigit(),
ชื่อ feature แต่ละอันอาจจะลองดูให้สม่ำเสมอกันครับ
เช่นตอนนี้ isspace ไม่มี () แต่ isdigit() มี ()
prevword แต่ prepostag (ลืม v?)

หรือมีวิธีการตั้งชื่อที่สั้นกระชับ แต่ยังอ่านเข้าใจอยู่ไหม
เช่น

- word, word-1, word+1
- word, prev_word, next_word
- curr_isspace, prev_isspace, next_isspace
- -2.pos, -1.pos, 0.pos, +1.pos, +2.pos

เลือกเอาตามที่สะดวก และรู้สึกว่าเห็นแล้วก็เข้าใจได้ง่ายครับ

2020-10-03 09:49 UTC, wannaphong commented on pythainlp/tokenize/crfcls.py
> +        "word.isdigit()": curr_word.isdigit(),
@bact แก้ไขเรียบร้อยแล้วครับ

2020-10-06 23:22 UTC, bact approved these changes

2020-10-07 08:46 UTC, merged