Deprecated syllable_tokenize #322
PyThaiNLP/pythainlp pull request #550
Opened 2021-04-14 09:53 UTC by wannaphong

syllable_tokenize is deprecated, use subword_tokenize instead

### What does this changes

Deprecated syllable_tokenize

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](https://github.com/PyThaiNLP/pythainlp/blob/dev/CONTRIBUTING.md) to this repository.

- [ ] Passed code styles and structures
- [ ] Passed code linting checks and unit test

2021-04-14 09:54 UTC, wannaphong commented
Todo
 

- [ ] move test set
- [ ] edit docs

2021-04-14 09:56 UTC, pep8speaks commented
Hello @wannaphong! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pythainlp/tokenize/core.py`](https://github.com/PyThaiNLP/pythainlp/blob/9d0453d7f85973e17cd92f492881d090195d4341/pythainlp/tokenize/core.py):

> [Line 425:80](https://github.com/PyThaiNLP/pythainlp/blob/9d0453d7f85973e17cd92f492881d090195d4341/pythainlp/tokenize/core.py#L425): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (102 > 79 characters)

2021-04-19 16:47 UTC, bact requested changes
Please remove "(default)" from "dict" in the docstring.

2021-04-19 16:47 UTC, bact commented on pythainlp/tokenize/core.py
> +        * *ssg* - CRF syllable segmenter for Thai
"dict" is not a default subword tokenization engine.

Current default is "tcc",
according to DEFAULT_SUBWORD_TOKENIZE_ENGINE constant in
https://github.com/PyThaiNLP/pythainlp/blob/dev/pythainlp/tokenize/__init__.py

"*dict* (default) - newmm..." should be just "* *dict* - newmm..."

2021-04-23 04:22 UTC, bact approved these changes

2021-04-23 07:49 UTC, merged