Add ThaiSum sentence segmentor
PyThaiNLP/pythainlp pull request #688
Opened 2022-07-22 21:39 UTC by chameleonTK

### What does this changes

Add a new sentence segmentor adopted from Chumpolsathien N., 2020. https://github.com/nakhunchumpolsathien/ThaiSum
It is a rule-based model from conjunction words and length of the sentences. 

### What was wrong

Just another option for the sentence segmentation model.

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](https://github.com/PyThaiNLP/pythainlp/blob/dev/CONTRIBUTING.md) to this repository.

- [/] Passed code styles and structures
- [/] Passed code linting checks and unit test

2022-07-22 21:39 UTC, pep8speaks commented
Hello @chameleonTK! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pythainlp/tokenize/core.py`](https://github.com/PyThaiNLP/pythainlp/blob/949e02ced12a2bf07064c068952f6bef04d8f512/pythainlp/tokenize/core.py):

> [Line 304:80](https://github.com/PyThaiNLP/pythainlp/blob/949e02ced12a2bf07064c068952f6bef04d8f512/pythainlp/tokenize/core.py#L304): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)

* In the file [`pythainlp/tokenize/thaisumcut.py`](https://github.com/PyThaiNLP/pythainlp/blob/949e02ced12a2bf07064c068952f6bef04d8f512/pythainlp/tokenize/thaisumcut.py):

> [Line 8:36](https://github.com/PyThaiNLP/pythainlp/blob/949e02ced12a2bf07064c068952f6bef04d8f512/pythainlp/tokenize/thaisumcut.py#L8): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 9:80](https://github.com/PyThaiNLP/pythainlp/blob/949e02ced12a2bf07064c068952f6bef04d8f512/pythainlp/tokenize/thaisumcut.py#L9): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (134 > 79 characters)
> [Line 10:37](https://github.com/PyThaiNLP/pythainlp/blob/949e02ced12a2bf07064c068952f6bef04d8f512/pythainlp/tokenize/thaisumcut.py#L10): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 11:17](https://github.com/PyThaiNLP/pythainlp/blob/949e02ced12a2bf07064c068952f6bef04d8f512/pythainlp/tokenize/thaisumcut.py#L11): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 32:9](https://github.com/PyThaiNLP/pythainlp/blob/949e02ced12a2bf07064c068952f6bef04d8f512/pythainlp/tokenize/thaisumcut.py#L32): [E117](https://duckduckgo.com/?q=pep8%20E117) over-indented
> [Line 34:80](https://github.com/PyThaiNLP/pythainlp/blob/949e02ced12a2bf07064c068952f6bef04d8f512/pythainlp/tokenize/thaisumcut.py#L34): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> [Line 49:80](https://github.com/PyThaiNLP/pythainlp/blob/949e02ced12a2bf07064c068952f6bef04d8f512/pythainlp/tokenize/thaisumcut.py#L49): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 60:80](https://github.com/PyThaiNLP/pythainlp/blob/949e02ced12a2bf07064c068952f6bef04d8f512/pythainlp/tokenize/thaisumcut.py#L60): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (95 > 79 characters)
> [Line 63:80](https://github.com/PyThaiNLP/pythainlp/blob/949e02ced12a2bf07064c068952f6bef04d8f512/pythainlp/tokenize/thaisumcut.py#L63): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 79 characters)
> [Line 72:27](https://github.com/PyThaiNLP/pythainlp/blob/949e02ced12a2bf07064c068952f6bef04d8f512/pythainlp/tokenize/thaisumcut.py#L72): [E701](https://duckduckgo.com/?q=pep8%20E701) multiple statements on one line (colon)
> [Line 73:30](https://github.com/PyThaiNLP/pythainlp/blob/949e02ced12a2bf07064c068952f6bef04d8f512/pythainlp/tokenize/thaisumcut.py#L73): [E701](https://duckduckgo.com/?q=pep8%20E701) multiple statements on one line (colon)
> [Line 84:80](https://github.com/PyThaiNLP/pythainlp/blob/949e02ced12a2bf07064c068952f6bef04d8f512/pythainlp/tokenize/thaisumcut.py#L84): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (262 > 79 characters)
> [Line 85:80](https://github.com/PyThaiNLP/pythainlp/blob/949e02ced12a2bf07064c068952f6bef04d8f512/pythainlp/tokenize/thaisumcut.py#L85): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (112 > 79 characters)
> [Line 88:80](https://github.com/PyThaiNLP/pythainlp/blob/949e02ced12a2bf07064c068952f6bef04d8f512/pythainlp/tokenize/thaisumcut.py#L88): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (161 > 79 characters)
> [Line 151:80](https://github.com/PyThaiNLP/pythainlp/blob/949e02ced12a2bf07064c068952f6bef04d8f512/pythainlp/tokenize/thaisumcut.py#L151): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 158:80](https://github.com/PyThaiNLP/pythainlp/blob/949e02ced12a2bf07064c068952f6bef04d8f512/pythainlp/tokenize/thaisumcut.py#L158): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 168:80](https://github.com/PyThaiNLP/pythainlp/blob/949e02ced12a2bf07064c068952f6bef04d8f512/pythainlp/tokenize/thaisumcut.py#L168): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (113 > 79 characters)
> [Line 192:80](https://github.com/PyThaiNLP/pythainlp/blob/949e02ced12a2bf07064c068952f6bef04d8f512/pythainlp/tokenize/thaisumcut.py#L192): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 201:80](https://github.com/PyThaiNLP/pythainlp/blob/949e02ced12a2bf07064c068952f6bef04d8f512/pythainlp/tokenize/thaisumcut.py#L201): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (111 > 79 characters)
> [Line 225:80](https://github.com/PyThaiNLP/pythainlp/blob/949e02ced12a2bf07064c068952f6bef04d8f512/pythainlp/tokenize/thaisumcut.py#L225): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 235:80](https://github.com/PyThaiNLP/pythainlp/blob/949e02ced12a2bf07064c068952f6bef04d8f512/pythainlp/tokenize/thaisumcut.py#L235): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (115 > 79 characters)
> [Line 265:80](https://github.com/PyThaiNLP/pythainlp/blob/949e02ced12a2bf07064c068952f6bef04d8f512/pythainlp/tokenize/thaisumcut.py#L265): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 267:23](https://github.com/PyThaiNLP/pythainlp/blob/949e02ced12a2bf07064c068952f6bef04d8f512/pythainlp/tokenize/thaisumcut.py#L267): [E701](https://duckduckgo.com/?q=pep8%20E701) multiple statements on one line (colon)
> [Line 268:24](https://github.com/PyThaiNLP/pythainlp/blob/949e02ced12a2bf07064c068952f6bef04d8f512/pythainlp/tokenize/thaisumcut.py#L268): [E701](https://duckduckgo.com/?q=pep8%20E701) multiple statements on one line (colon)
> [Line 269:23](https://github.com/PyThaiNLP/pythainlp/blob/949e02ced12a2bf07064c068952f6bef04d8f512/pythainlp/tokenize/thaisumcut.py#L269): [E701](https://duckduckgo.com/?q=pep8%20E701) multiple statements on one line (colon)
> [Line 270:23](https://github.com/PyThaiNLP/pythainlp/blob/949e02ced12a2bf07064c068952f6bef04d8f512/pythainlp/tokenize/thaisumcut.py#L270): [E701](https://duckduckgo.com/?q=pep8%20E701) multiple statements on one line (colon)
> [Line 325:80](https://github.com/PyThaiNLP/pythainlp/blob/949e02ced12a2bf07064c068952f6bef04d8f512/pythainlp/tokenize/thaisumcut.py#L325): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 335:27](https://github.com/PyThaiNLP/pythainlp/blob/949e02ced12a2bf07064c068952f6bef04d8f512/pythainlp/tokenize/thaisumcut.py#L335): [E701](https://duckduckgo.com/?q=pep8%20E701) multiple statements on one line (colon)
> [Line 336:30](https://github.com/PyThaiNLP/pythainlp/blob/949e02ced12a2bf07064c068952f6bef04d8f512/pythainlp/tokenize/thaisumcut.py#L336): [E701](https://duckduckgo.com/?q=pep8%20E701) multiple statements on one line (colon)
> [Line 343:29](https://github.com/PyThaiNLP/pythainlp/blob/949e02ced12a2bf07064c068952f6bef04d8f512/pythainlp/tokenize/thaisumcut.py#L343): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2022-07-23 10:09 UTC, wannaphong commented on pythainlp/tokenize/thaisumcut.py
> +            tokens = pythainlp.word_tokenize(text.strip(), keep_whitespace=True)
Can you use replace `pythainlp.word_tokenize(text.strip(), keep_whitespace=True)` with `word_tokenize(text.strip(), keep_whitespace=True)` by `from pythainlp.tokenize import word_tokenize` at the head file?

2022-07-23 10:11 UTC, wannaphong requested changes

2022-07-23 10:11 UTC, wannaphong commented on pythainlp/tokenize/thaisumcut.py
> +import pythainlp
Can you use replace `import pythainlp` with `from pythainlp.tokenize import word_tokenize`?

2022-07-23 10:20 UTC, wannaphong commented
I think you should change `import pythainlp.word_tokenize` to `from pythainlp.tokenize import word_tokenize` becase `from pythainlp.tokenize import word_tokenize` is faster than `import pythainlp.word_tokenize` by specify the function.

2022-07-23 17:53 UTC, chameleonTK commented
Fixed as suggested :D

2022-07-23 18:24 UTC, wannaphong commented
@chameleonTK Can you fix pep8? If you can't fix, It is not problem because I can fix.

2022-07-23 19:17 UTC, chameleonTK commented
> @chameleonTK Can you fix pep8? If you can't fix, It is not problem because I can fix.

I have fixed some but `line too long` warnings are not sensible to me so I kept them as they are. Feel free to fix them.

2022-07-23 20:45 UTC, wannaphong approved these changes
Thank you!

2022-07-23 20:45 UTC, merged