add khavee to pythainlp
PyThaiNLP/pythainlp pull request #777
Opened 2023-03-16 09:32 UTC by kangkengkhadev

### What does this changes

Brief summary of the changes

### What was wrong

Description of what was the root cause of the issue.

### How this fixes it

Description of how the changes fix the issue.

Fixes #...

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](https://github.com/PyThaiNLP/pythainlp/blob/dev/CONTRIBUTING.md) to this repository.

- [ ] Passed code styles and structures
- [ ] Passed code linting checks and unit test

2023-03-16 09:33 UTC, kangkengkhadev commented
Add Khavee the poem verifier to Pythainlp

2023-03-16 20:21 UTC, wannaphong requested changes
Thank you for sent this pull request! I have a comment that you can edit before I will merging this  pull request.

2023-03-16 20:21 UTC, wannaphong commented on pythainlp/khavee/__init__.py
Can you add

```python
__all__ = ["KhaveeVerifier"]

from pythainlp.khavee.core import KhaveeVerifier
```

2023-03-17 08:18 UTC, wannaphong approved these changes

2023-03-17 08:22 UTC, wannaphong commented
Thank you!

2023-03-17 08:22 UTC, merged