add aek/too checker function to khavee
PyThaiNLP/pythainlp pull request #779
Opened 2023-03-17 10:56 UTC by HRNPH

### What does this changes
Add aek/too word checking function into khavee

### What was wrong

there's no aek/too checking functionality in khavee yet

### How this fixes it

Add aek/too word checking function into khavee

Fixes #...

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](https://github.com/PyThaiNLP/pythainlp/blob/dev/CONTRIBUTING.md) to this repository.

- [ ] Passed code styles and structures
- [ ] Passed code linting checks and unit test

2023-03-17 15:40 UTC, wannaphong requested changes
Thank you for this pull request! I have comments that you can fix.

2023-03-17 15:40 UTC, wannaphong commented on pythainlp/khavee/core.py
> +    def check_aek_too(self, text: str or List[str]) -> str or bool or List[str or bool]:
- `text: str or List[str]` should be text `Union[List[str], str]`
- `str or bool or List[str or bool]` should be `Union[List[bool], List[str], bool, str]`

2023-03-17 15:40 UTC, wannaphong commented on pythainlp/khavee/core.py
> +        :rtype: str or bool or list[str or bool]
`str or bool or list[str or bool]` should be `Union[List[bool], List[str], bool, str]`

2023-03-17 15:40 UTC, wannaphong commented on tests/test_khavee.py
> +        self.assert_(kv.check_aek_too(['หนม', 'หน่ม', 'หน้ม']), [False, 'aek', 'too'])
add blank newline after this line

2023-03-17 15:40 UTC, wannaphong commented on pythainlp/khavee/core.py
> +        Check if the word is aek or too or False(not both)
`คำเอกโท` in English?

2023-03-17 18:29 UTC, HRNPH commented on pythainlp/khavee/core.py
> +        Check if the word is aek or too or False(not both)
thai tonal word checker?
https://dict.longdo.com/search/-%E0%B9%80%E0%B8%AD%E0%B8%81%E0%B9%82%E0%B8%97%E0%B8%A9-

2023-03-17 18:37 UTC, HRNPH commented on pythainlp/khavee/core.py
> +    def check_aek_too(self, text: str or List[str]) -> str or bool or List[str or bool]:
changed👍

2023-03-17 18:37 UTC, HRNPH commented on pythainlp/khavee/core.py
> +        :rtype: str or bool or list[str or bool]
changed👍

2023-03-17 18:39 UTC, HRNPH commented on tests/test_khavee.py
> +        self.assert_(kv.check_aek_too(['หนม', 'หน่ม', 'หน้ม']), [False, 'aek', 'too'])
changed👍

2023-03-17 21:57 UTC, cstorm125 commented
wow

2023-03-18 02:09 UTC, wannaphong approved these changes
💯

2023-03-18 02:10 UTC, merged