fix some bugs and add check_karu_lahu function
PyThaiNLP/pythainlp pull request #787
Opened 2023-04-02 21:09 UTC by kangkengkhadev

### What does this changes

Brief summary of the changes

### What was wrong

Description of what was the root cause of the issue.

### How this fixes it

Description of how the changes fix the issue.

Fixes #...

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](https://github.com/PyThaiNLP/pythainlp/blob/dev/CONTRIBUTING.md) to this repository.

- [ ] Passed code styles and structures
- [ ] Passed code linting checks and unit test

2023-04-03 06:23 UTC, wannaphong requested changes

2023-04-03 06:23 UTC, wannaphong commented on pythainlp/khavee/core.py
> +        :param str or list[str] text: Thai word or list of Thai words, bool dead_syllable_as_aek: if True, dead syllable will be considered as aek
Can you change this line by create new line?

```python
:param Union[List[str], str] text: Thai word or list of Thai words
:param bool dead_syllable_as_aek: if True, dead syllable will be considered as aek
```

2023-04-03 23:38 UTC, kangkengkhadev commented on pythainlp/khavee/core.py
> +        :param str or list[str] text: Thai word or list of Thai words, bool dead_syllable_as_aek: if True, dead syllable will be considered as aek
Sure

2023-04-04 07:05 UTC, wannaphong approved these changes

2023-04-04 07:05 UTC, wannaphong commented
Thank you!

2023-04-04 07:05 UTC, merged