Add Volubilis corpus
PyThaiNLP/pythainlp pull request #870
Opened 2023-11-30 04:09 UTC by konbraphat51

### What does this changes

Add an optional corpus of Wikipedia titles.
* wikipedia_titles() function
* license description

Fixes #858 

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](https://github.com/PyThaiNLP/pythainlp/blob/dev/CONTRIBUTING.md) to this repository.

- [x] Passed code styles and structures
- [ ] Passed code linting checks and unit test

2023-11-30 04:52 UTC, konbraphat51 commented
Not sure why coverall doesn't recognize test code of `volubilis()`

2023-11-30 05:01 UTC, konbraphat51 commented
Review please

2023-11-30 16:07 UTC, bact requested changes
After updating license info, I think we are good to go.

2023-11-30 16:07 UTC, bact commented on pythainlp/corpus/corpus_license.md
> +Corpus of Wikipedia titles (volubilis.txt) was processed by konbraphat51 (https://github.com/konbraphat51/Thai_Dictionary_Cleaner/tree/main)
I guess this should be Volubilis dictionary and not Wikipedia titles.

2023-11-30 16:07 UTC, bact commented on pythainlp/corpus/corpus_license.md
> +The original data is Volubilis Database from [Volubilis](https://belisan-volubilis.blogspot.com/) which Francis Bastien has created.
Maybe add version info somewhere around here.

VOLUBILIS 23.1 (Mar. 2023)

2023-11-30 18:09 UTC, konbraphat51 commented on pythainlp/corpus/corpus_license.md
> +Corpus of Wikipedia titles (volubilis.txt) was processed by konbraphat51 (https://github.com/konbraphat51/Thai_Dictionary_Cleaner/tree/main)
oh my god.
Sorry for that (copy & paste)

I fixed it

2023-11-30 18:09 UTC, konbraphat51 commented on pythainlp/corpus/corpus_license.md
> +The original data is Volubilis Database from [Volubilis](https://belisan-volubilis.blogspot.com/) which Francis Bastien has created.
Added!

2023-11-30 18:09 UTC, konbraphat51 commented
Okey, review again please

2023-12-01 04:05 UTC, wannaphong approved these changes

2023-12-01 05:09 UTC, bact approved these changes

2023-12-01 05:09 UTC, merged