Updated crfcut.py
PyThaiNLP/pythainlp pull request #905
Opened 2024-04-01 09:29 UTC by varunkatiyar819

Crfcut creating issues for split using terminal punctuation commonly '.' (full stop) which should be treated as end of the sentence, Modified the function such that it should split using terminal punctuations and avoid any kind of empty strings.

### What does this changes

Brief summary of the changes

### What was wrong

Description of what was the root cause of the issue.

### How this fixes it

Description of how the changes fix the issue.

Fixes #...

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](https://github.com/PyThaiNLP/pythainlp/blob/dev/CONTRIBUTING.md) to this repository.

- [ ] Passed code styles and structures
- [ ] Passed code linting checks and unit test

2024-04-01 09:29 UTC, pep8speaks commented
Hello @varunkatiyar819! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pythainlp/tokenize/crfcut.py`](https://github.com/PyThaiNLP/pythainlp/blob/c37670dbc6e8223d7674ef2bdfad83955507ead1/pythainlp/tokenize/crfcut.py):

> [Line 201:1](https://github.com/PyThaiNLP/pythainlp/blob/c37670dbc6e8223d7674ef2bdfad83955507ead1/pythainlp/tokenize/crfcut.py#L201): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 202:5](https://github.com/PyThaiNLP/pythainlp/blob/c37670dbc6e8223d7674ef2bdfad83955507ead1/pythainlp/tokenize/crfcut.py#L202): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 204:7](https://github.com/PyThaiNLP/pythainlp/blob/c37670dbc6e8223d7674ef2bdfad83955507ead1/pythainlp/tokenize/crfcut.py#L204): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 205:11](https://github.com/PyThaiNLP/pythainlp/blob/c37670dbc6e8223d7674ef2bdfad83955507ead1/pythainlp/tokenize/crfcut.py#L205): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 206:1](https://github.com/PyThaiNLP/pythainlp/blob/c37670dbc6e8223d7674ef2bdfad83955507ead1/pythainlp/tokenize/crfcut.py#L206): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 207:7](https://github.com/PyThaiNLP/pythainlp/blob/c37670dbc6e8223d7674ef2bdfad83955507ead1/pythainlp/tokenize/crfcut.py#L207): [E114](https://duckduckgo.com/?q=pep8%20E114) indentation is not a multiple of four (comment)
> [Line 207:7](https://github.com/PyThaiNLP/pythainlp/blob/c37670dbc6e8223d7674ef2bdfad83955507ead1/pythainlp/tokenize/crfcut.py#L207): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 208:7](https://github.com/PyThaiNLP/pythainlp/blob/c37670dbc6e8223d7674ef2bdfad83955507ead1/pythainlp/tokenize/crfcut.py#L208): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 209:11](https://github.com/PyThaiNLP/pythainlp/blob/c37670dbc6e8223d7674ef2bdfad83955507ead1/pythainlp/tokenize/crfcut.py#L209): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 215:9](https://github.com/PyThaiNLP/pythainlp/blob/c37670dbc6e8223d7674ef2bdfad83955507ead1/pythainlp/tokenize/crfcut.py#L215): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 215:101](https://github.com/PyThaiNLP/pythainlp/blob/c37670dbc6e8223d7674ef2bdfad83955507ead1/pythainlp/tokenize/crfcut.py#L215): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (110 > 100 characters)

2024-04-01 14:24 UTC, wannaphong commented on pythainlp/tokenize/crfcut.py
> +        if(toks[idx].strip().endswith(('!', '.', '?'))):
Can you remove ( and ) after `if`?

2024-04-01 14:58 UTC, varunkatiyar819 commented on pythainlp/tokenize/crfcut.py
> +        if(toks[idx].strip().endswith(('!', '.', '?'))):
Sure!

2024-04-01 15:04 UTC, varunkatiyar819 commented on pythainlp/tokenize/crfcut.py
> +        if(toks[idx].strip().endswith(('!', '.', '?'))):
Required changes are updated! Thanks

2024-04-02 15:34 UTC, wannaphong approved these changes
It look great!

This pull request change crfcut.

Before
```python
>>> sent_tokenize("สวัสดีชาวโลก. \n โลกนี้เต็มไปด้วยความลึกลับ")
['สวัสดีชาวโลก. \n โลกนี้เต็มไปด้วยความลึกลับ']
>>> sent_tokenize("สวัสดีชาวโลก! \n โลกนี้เต็มไปด้วยความลึกลับ")
['สวัสดีชาวโลก! \n โลกนี้เต็มไปด้วยความลึกลับ']
```
After
```python
>>> sent_tokenize("สวัสดีชาวโลก. \n โลกนี้เต็มไปด้วยความลึกลับ")
['สวัสดีชาวโลก.', ' \n โลกนี้เต็มไปด้วยความลึกลับ']
>>> sent_tokenize("สวัสดีชาวโลก! \n โลกนี้เต็มไปด้วยความลึกลับ")
['สวัสดีชาวโลก!', ' \n โลกนี้เต็มไปด้วยความลึกลับ']
```

Thank you!

2024-04-03 06:11 UTC, wannaphong requested changes
It look the test is break. Can you fix? @varunkatiyar819 

`['ฉันไปโรงเรียน เธอไปโรงพยาบาล'] != ['ฉันไปโรงเรียน ', 'เธอไปโรงพยาบาล']`

2024-04-03 07:53 UTC, varunkatiyar819 commented
> It look the test is break. Can you fix? @varunkatiyar819
> 
> `['ฉันไปโรงเรียน เธอไปโรงพยาบาล'] != ['ฉันไปโรงเรียน ', 'เธอไปโรงพยาบาล']`

Logic for the Code is been modified and tested as well. Please do have a check. Thanks

2024-04-03 10:16 UTC, wannaphong approved these changes
Thank you!

2024-04-03 10:17 UTC, merged